### ISSUE TITLE
Customizing webpack-dev-server

### ISSUE THREAD

**Issue by aghArdeshir** [monkey-patches/monkey-react-scripts#1]
HI!
I want my `devServer` to `writeToDisk`.
I didn't find any documentation related to customizing `devServer`.
Can `monkey-react-scripts` do this?
Thanks

**Comment by smmoosavi** [comment]
Hi

`monkey-react-scripts` helps you to customize your webpack config, but you cannot change devServer directly.

https://webpack.js.org/configuration/dev-server/#devserverwritetodisk-

```js
module.exports = function(webpackConfig, isDevelopment) {
  webpackConfig.devServer = {writeToDisk: true}
}
```
